### ISSUE TITLE
Error when running dev or build

### ISSUE THREAD

**Issue by vemonet** [Simon-Laux/tauri-emoji-mart-app#2]
Hi @Simon-Laux , thanks for this nice app, I love its simplicity! The simplest tauri setup + emoji web component =  an emoji desktop app in a few dozen lines of code!

I tried to run the main branch but got the same error when running `yarn tauri dev` or `yarn tauri build`:

```
thread 'main' panicked at 'data.len() must fit the width, height, and row_stride',
~/.cargo/registry/src/github.com-1ecc6299db9ec823/gdk-pixbuf-0.15.11/src/pixbuf.rs:52:13
```

Any idea what it could be due to?

According to a few issues it seems to be related to the tauri icons: https://github.com/tauri-apps/tauri/issues/6117 and https://github.com/tauri-apps/tauri/issues/3877, but you seems to be using the default tauri icons

I am running on Fedora 38 with GNOME 44

**Comment by Simon-Laux** [comment]
Maybe we should update the project to use the newest available tauri version and see if it fixes the issue. I think I also had the same issue on the cinnamon desktop.
